{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fluentd-opensearch.fullname" . }}
  labels:
    {{- include "fluentd-opensearch.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
- kind: ServiceAccount
  name: {{ if .Values.serviceAccount.name }}{{ .Values.serviceAccount.name }}{{ else }}{{ include "fluentd-opensearch.fullname" . }}{{ end }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "fluentd-opensearch.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
