{{- if or (.Values.serviceMonitor.enabled) (.Values.serviceMetric.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd-opensearch.metricsServiceName" . }}
  labels:
    {{- include "fluentd-opensearch.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  type: {{ .Values.serviceMonitor.type }}
  ports:
    - name: metrics
      port: {{ .Values.serviceMonitor.port }}
      targetPort: {{ .Values.serviceMonitor.port }}
  selector:
    {{- include "fluentd-opensearch.selectorLabels" . | nindent 4 }}
{{- end }}
