{{- if .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "fluentd-opensearch.fullname" . }}
  labels:
    {{- include "fluentd-opensearch.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "fluentd-opensearch.fullname" . }}
{{- end }}
