{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd-opensearch.serviceAccountName" . }}
  labels:
    {{- include "fluentd-opensearch.labels" . | nindent 4 }}
    addonmanager.kubernetes.io/mode: Reconcile
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
